FROM ubuntu
LABEL Author=sherylynn@outlook.com

WORKDIR /home
COPY seafile_install_ubt.sh \
     /home/
COPY sources.list /etc/apt/sources.list

#RUN bash seafile_install_ubt.sh 
#apt的命令还是要集成在run中好，不然会出事
#把seafile的安装拿到外面去
RUN apt update -y && \
    apt install -y wget && \
    apt-get install -y python && \
    apt-get install -y python2.7 libpython2.7 python-setuptools python-imaging python-ldap python-urllib3 ffmpeg python-pip python-mysqldb python-memcache && \
    apt clean

RUN pip install pillow moviepy

ADD seafile_config.sh /home/seafile_config.sh
RUN chmod 777 seafile_config.sh
EXPOSE 8082
EXPOSE 8000
CMD [ "/bin/bash" ]
#python2.7 ./seafile-server-6.2.4/setup-seafile-mysql.py