version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 3800:8000
      - 9000
    volumes:
      - /etc/drone:/var/lib/drone/
    restart: always
    env_file:
      - /etc/drone/drone.env
    environment:
      - DRONE_OPEN=true
#      - DRONE_GITHUB=false
#      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
#      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_GOGS=true
#      - DRONE_GOGS_URL=${GOGS_HOST}  ${}没法获取到.env里设定的环境变量
  drone-agent:
    image: drone/drone:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - /etc/drone/drone.env
    environment:
#      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SERVER=drone-server:9000