version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 3800:8000
      - 9000
    volumes:
      - /etc/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
#      - DRONE_GITHUB=false
#      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
#      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=${DRONE_HOST}
  drone-agent:
    image: drone/drone:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
#      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}