version: '2'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ~/nextcloud/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - ~/nextcloud/html:/var/www/html
    restart: always
  
  web:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
    links:
      - app
    #this docker path is /etc/Caddyfile
    volumes:
      - ~/nextcloud/Caddyfile:/etc/Caddyfile:ro
    volumes_from:
      - app
    restart: always