version: '2'

services:
  cloud_db:
    container_name: cloud_db
    #image: mariadb
    image: mysql
    restart: always
    volumes:
      - /mnt/hgfs/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: cloud_app
    image: nextcloud:fpm
    links:
      - cloud_db
    ports:
      - "9000:9000"
    volumes:
      - /mnt/hgfs/nextcloud/html:/var/www/html
    restart: always