version: '2'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - /mnt/hgfs/nextcloud/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - /mnt/hgfs/nextcloud/html:/var/www/html
    restart: always
  
  web:
    image: abiosoft/caddy
    ports:
      - 8080:80
    links:
      - app
    #this docker path is /etc/Caddyfile
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
    volumes_from:
      - app
    restart: always