#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]lynn@n4\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export http_proxy=http://127.0.0.1:8087/
export https_proxy=http://127.0.0.1:8087/
export GOPATH=$HOME/go
