#!/data/data/com.termux/files/usr/bin/bash
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHROOT_TOOL="$SCRIPT_DIR/chroot/cli.sh"
PULSE_PORT="${PULSE_PORT:-4713}"
PULSE_SERVER_ADDR="tcp:127.0.0.1:${PULSE_PORT}"
MODULE_TCP_ARGS="auth-ip-acl=127.0.0.1 auth-anonymous=1 port=${PULSE_PORT}"
PROFILE_FILE="/etc/profile.d/termux-pulse.sh"

log() { printf '[termux-audio] %s\n' "$*"; }
warn() { printf '[termux-audio] WARN: %s\n' "$*" >&2; }
die() { printf '[termux-audio] ERROR: %s\n' "$*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

pulse_running() {
  pulseaudio --check >/dev/null 2>&1 || pgrep -x pulseaudio >/dev/null 2>&1
}

module_loaded() {
  local name="$1"
  pactl list short modules 2>/dev/null | awk '{print $2}' | grep -Fxq "$name"
}

find_module_file() {
  local name="$1"
  local base
  for base in "$PREFIX/lib/pulseaudio/modules" "$PREFIX/lib/pulse" "$PREFIX/lib"; do
    [ -d "$base" ] || continue
    find "$base" -type f -name "${name}.so" -print -quit 2>/dev/null && return 0
  done
  return 1
}

ensure_pulseaudio() {
  have pulseaudio || die "未安装 pulseaudio。请先 pkg install pulseaudio"
  have pactl || die "未找到 pactl。请重新安装 pulseaudio 包"

  if pulse_running; then
    log "PulseAudio 已运行"
    return 0
  fi

  log "启动 Termux PulseAudio"
  pulseaudio --start --exit-idle-time=-1 || die "PulseAudio 启动失败"
  sleep 1
  pulse_running || die "PulseAudio 未保持运行"
}

ensure_tcp_module() {
  if module_loaded module-native-protocol-tcp; then
    log "module-native-protocol-tcp 已加载"
    return 0
  fi

  log "加载 module-native-protocol-tcp (127.0.0.1:${PULSE_PORT})"
  pactl load-module module-native-protocol-tcp $MODULE_TCP_ARGS >/dev/null || \
    die "无法加载 module-native-protocol-tcp"
}

try_load_android_audio() {
  local role="$1"
  local candidates=()
  case "$role" in
    sink)
      candidates=(module-aaudio-sink module-sles-sink)
      ;;
    source)
      candidates=(module-aaudio-source module-sles-source)
      ;;
    *) return 1 ;;
  esac

  local m
  for m in "${candidates[@]}"; do
    if module_loaded "$m"; then
      log "$m 已加载"
      return 0
    fi
    if find_module_file "$m" >/dev/null 2>&1; then
      log "尝试加载 $m"
      if pactl load-module "$m" >/dev/null 2>&1; then
        log "$m 加载成功"
        return 0
      fi
      warn "$m 存在但加载失败"
    fi
  done
  return 1
}

print_audio_state() {
  echo "=== PulseAudio server ==="
  pactl info 2>&1 || true
  echo
  echo "=== Sinks ==="
  pactl list short sinks 2>&1 || true
  echo
  echo "=== Sources ==="
  pactl list short sources 2>&1 || true
  echo
  echo "=== Android audio modules ==="
  pactl list short modules 2>/dev/null | grep -E 'native-protocol-tcp|aaudio|sles' || true
}

chroot_exec() {
  [ -f "$CHROOT_TOOL" ] || die "未找到 $CHROOT_TOOL"
  bash "$CHROOT_TOOL" exec "$@"
}

chroot_config() {
  local content
  content=$(cat <<EOF2
# Generated by ~/sh/termux/termux_audio_bridge.sh
# Route chroot PulseAudio clients to the Termux PulseAudio server.
export PULSE_SERVER=${PULSE_SERVER_ADDR}
EOF2
)

  log "写入 chroot ${PROFILE_FILE}"
  chroot_exec "mkdir -p /etc/profile.d && cat > ${PROFILE_FILE} <<'EOF_PROFILE'
${content}
EOF_PROFILE
chmod 644 ${PROFILE_FILE}"

  log "验证 chroot 到 Termux PulseAudio 的连接"
  chroot_exec "PULSE_SERVER=${PULSE_SERVER_ADDR} pactl info || true"
}

doctor() {
  echo "=== Termux Audio Bridge doctor ==="
  echo "PREFIX=${PREFIX:-<unset>}"
  echo "PULSE_SERVER target=${PULSE_SERVER_ADDR}"
  echo

  for cmd in pulseaudio pactl pkg pgrep; do
    if have "$cmd"; then
      echo "[OK] $cmd -> $(command -v "$cmd")"
    else
      echo "[MISS] $cmd"
    fi
  done

  echo
  echo "=== Candidate Android audio modules ==="
  local m path
  for m in module-aaudio-sink module-aaudio-source module-sles-sink module-sles-source; do
    path="$(find_module_file "$m" 2>/dev/null || true)"
    if [ -n "$path" ]; then
      echo "[FOUND] $m -> $path"
    else
      echo "[MISS]  $m"
    fi
  done

  echo
  if pulse_running; then
    echo "[OK] PulseAudio running"
    print_audio_state
  else
    echo "[INFO] PulseAudio not running"
  fi

  echo
  if [ -f "$CHROOT_TOOL" ]; then
    echo "[OK] chroot cli -> $CHROOT_TOOL"
  else
    echo "[MISS] chroot cli -> $CHROOT_TOOL"
  fi
}

start_bridge() {
  ensure_pulseaudio
  ensure_tcp_module

  if ! try_load_android_audio sink; then
    warn "没有可用的 AAudio/OpenSL ES sink。先看 doctor 输出；部分 Termux PulseAudio 构建会自动提供 Android sink。"
  fi
  if ! try_load_android_audio source; then
    warn "没有可用的 AAudio/OpenSL ES source。扬声器仍可能可用；麦克风需后续单独解决。"
  fi

  log "音频桥已启动；chroot 客户端应使用 PULSE_SERVER=${PULSE_SERVER_ADDR}"
  print_audio_state
}

stop_bridge() {
  if ! pulse_running; then
    log "PulseAudio 未运行"
    return 0
  fi

  local ids
  ids="$(pactl list short modules 2>/dev/null | awk '$2=="module-native-protocol-tcp" {print $1}')"
  if [ -n "$ids" ]; then
    while read -r id; do
      [ -n "$id" ] && pactl unload-module "$id" >/dev/null 2>&1 || true
    done <<< "$ids"
    log "已卸载 native TCP bridge"
  fi
  log "未停止 PulseAudio 本体，避免影响你现有 tstart 服务"
}

test_bridge() {
  ensure_pulseaudio
  ensure_tcp_module
  log "Termux 本地播放测试"
  if have paplay; then
    local wav=""
    for wav in \
      "$PREFIX/share/sounds/freedesktop/stereo/complete.oga" \
      "$PREFIX/share/sounds/freedesktop/stereo/bell.oga"; do
      if [ -f "$wav" ]; then
        paplay "$wav" && break
      fi
    done
    [ -n "$wav" ] || warn "未找到系统测试音频；可手动执行 paplay <wav-file>"
  else
    warn "没有 paplay，跳过 Termux 本地播放测试"
  fi

  if [ -f "$CHROOT_TOOL" ]; then
    log "chroot PulseAudio 连通性测试"
    chroot_exec "PULSE_SERVER=${PULSE_SERVER_ADDR} pactl info && echo && pactl list short sinks && echo && pactl list short sources" || true
  fi
}

usage() {
  cat <<'EOF2'
Termux / chroot Android audio bridge experiment

Usage:
  bash ~/sh/termux/termux_audio_bridge.sh doctor
  bash ~/sh/termux/termux_audio_bridge.sh start
  bash ~/sh/termux/termux_audio_bridge.sh status
  bash ~/sh/termux/termux_audio_bridge.sh chroot-config
  bash ~/sh/termux/termux_audio_bridge.sh test
  bash ~/sh/termux/termux_audio_bridge.sh stop

Commands:
  doctor         检查 PulseAudio、AAudio/OpenSL ES 模块和 chroot 工具
  start          启动/复用 Termux PulseAudio，开放 localhost native protocol，并尝试 Android 音频模块
  status         显示当前 sinks/sources/modules
  chroot-config  在 chroot 写入 /etc/profile.d/termux-pulse.sh
  test           测试 Termux 与 chroot PulseAudio 连通性
  stop           仅卸载 native TCP bridge，不停止 PulseAudio 本体

Environment:
  PULSE_PORT=4713 可覆盖默认端口
EOF2
}

main() {
  case "${1:-status}" in
    doctor) doctor ;;
    start) start_bridge ;;
    status) ensure_pulseaudio; print_audio_state ;;
    chroot-config) ensure_pulseaudio; ensure_tcp_module; chroot_config ;;
    test) test_bridge ;;
    stop) stop_bridge ;;
    -h|--help|help) usage ;;
    *) usage; exit 2 ;;
  esac
}

main "$@"
